
image: node:16.17.0
before_script: npm ci

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

stages:
  - setup
  - test
  - build

unit_tests:
  stage: test
  script:
    - npm test -- --no-watch --browsers=ChromeHeadlessCI

end_to_end_tests:
  stage: test
  image:
  script:
    - npx cypress run

build_image:
  stage: build
  image: docker:20.10.18
  services:
    - docker:20.10.18-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - ng build --prod
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG